### ISSUE TITLE
Cannot import the name 'YOLO'

### ISSUE THREAD

**Issue by omarabolmagd** [mizarzulfa/Traffic-Counting-using-YOLO-Tensorflow-SORT#1]
I get this message when I run main.py

File "main.py", line 9, in <module>
    from yolo import YOLO 
ImportError: cannot import name 'YOLO'

**Comment by mizarzulfa** [comment]
> I get this message when I run main.py
> 
> File "main.py", line 9, in
> from yolo import YOLO
> ImportError: cannot import name 'YOLO'

Hi there,
File already added! and you can get yolo file from https://pjreddie.com/darknet/yolo/

Cheers!

**Comment by omarabolmagd** [comment]
> > I get this message when I run main.py
> > File "main.py", line 9, in
> > from yolo import YOLO
> > ImportError: cannot import name 'YOLO'
> 
> Hi there,
> File already added! and you can get yolo file from https://pjreddie.com/darknet/yolo/
> 
> Cheers!
Sorry, which file are you referring to?

**Comment by mizarzulfa** [comment]
> > > I get this message when I run main.py
> > > File "main.py", line 9, in
> > > from yolo import YOLO
> > > ImportError: cannot import name 'YOLO'
> > 
> > 
> > Hi there,
> > File already added! and you can get yolo file from https://pjreddie.com/darknet/yolo/
> > Cheers!
> > Sorry, which file are you referring to?

You can check here: https://github.com/mizarzulfa/Traffic-Counting-using-YOLO-Tensorflow-SORT/blob/master/yolo.py | You're getting an error message because you don't have yolo.py

Hope this help
Cheers,

**Comment by omarabolmagd** [comment]
> > I get this message when I run main.py
> > File "main.py", line 9, in
> > from yolo import YOLO
> > ImportError: cannot import name 'YOLO'
> 
> Hi there,
> File already added! and you can get yolo file from https://pjreddie.com/darknet/yolo/
> 
> Cheers!





> > > > I get this message when I run main.py
> > > > File "main.py", line 9, in
> > > > from yolo import YOLO
> > > > ImportError: cannot import name 'YOLO'
> > > 
> > > 
> > > Hi there,
> > > File already added! and you can get yolo file from https://pjreddie.com/darknet/yolo/
> > > Cheers!
> > > Sorry, which file are you referring to?
> 
> You can check here: https://github.com/mizarzulfa/Traffic-Counting-using-YOLO-Tensorflow-SORT/blob/master/yolo.py | You're getting an error message because you don't have yolo.py
> 
> Hope this help
> Cheers,

Thaaanks a lot
